export const CHANGE_TITLE = 'changeTitle'
export const CHANGE_CONTENT = 'changeContent'
export const CHANGE_BG = 'changeBg'
export const POPULATE_SHOPPING_LISTS = 'populateShoppingLists'
export const POPULATE_POSTS = 'populatePosts'
